### ISSUE TITLE
Cant find any nodes

### ISSUE THREAD

**Issue by sai5567** [daaanstraight/AirPlonk#2]
hey i cant find any nodes when i try to scan
 its always saying no nodes found
both on mac os and android

im using bigsur 11.1 hackintosh

**Comment by daaanstraight** [comment]
Hi.

Please try run
``` 
airplonk -t 
 ```
 You have to enable remote login on your mac. 
Go to System Preferences > Sharing, then check the remote login button and allow access for all users. 
It should look like this:
![Screenshot 2021-01-23 at 3 34 10 PM](https://user-images.githubusercontent.com/69418528/105566333-7c7a5d80-5d90-11eb-9b4e-91b9dab62c11.png)

Let me know how that goes, then I can close the issue! :)

**Comment by sai5567** [comment]
yeah now its showing my laptop

thnx

if u mention the procedure for connecting the devices in readme.md then it will be helpful for others who are new to this

**Comment by daaanstraight** [comment]
Note taken, and I will do so. Thanks for the input. 👍
