### ISSUE TITLE
Isn't working

### ISSUE THREAD

**Issue by madhav0922** [daaanstraight/AirPlonk#3]
I tried to plonk stuff between my hackintosh, Mac, phone and tab. It is just unable to find the nodes, even after enabling remote login. My phone is Samsung Galaxy S20+ and tab is Samsung Galaxy Tab S6 lite.

**Comment by gomesdigital** [comment]
Hi @madhav0922,

Thanks for reaching out.

Firstly, can you confirm your devices are on the same local network?

**Comment by madhav0922** [comment]
Yes, they are, i am able to access my mac using termux command line, however not via airplonk

**Comment by gomesdigital** [comment]
Right... if you are not receiving any error output and simply getting 'No
nodes found :(' then I can think of 2 things:

1. Your remote login service is not listening on port 22. Port 22 is the
default port for remote logins. AirPlonk looks for nodes listening on port
22.
2. Your IP address is for some reason not in range of where AirPlonk is
looking, although I doubt this. If you'd like you can send me your local IP
address and I
can try to replicate the issue -  emphasis on local IP, not your public one.

If you are able to ssh into your Mac via termux and haven't redirected any
ports, then it is hard to say why AirPlonk is not working.

Please do confirm if the issue has been resolved or you can still not get
it to work.

Cheers,
Dan

**Comment by madhav0922** [comment]
Here's my local IP address: 192.168.29.145
I have an M1 Mac and a hackintosh to begin with.

Also, yes I am able to ssh into both the devices and haven't redirected any ports, however not via AirPlonk

Is there a way to know the port in use?.. like debug, that might be helpful

Thanks
