### ISSUE TITLE
Rsync version check not working for Rsync v3.2+

### ISSUE THREAD

**Issue by patrickm663** [daaanstraight/AirPlonk#8]
Hi @gomesdigital

I was recently testing AirPlonk on Manjaro and came across a change in how Rsync displays its current version after 3.1. It now reads:

`$ rsync --version`
`rsync  version v3.2.3  protocol version 31`

Because of this, it does not recognise the major version, since "v3" gets sent to the if-statement, which it can't interpret.

Cheers
Patrick

**Comment by gomesdigital** [comment]
Hey @patrickm663,

This was a precaution for Mac OS where rsync is being shipped with versions prior to 3.0.0. We need ^3.0.0 to tap into the transfer progress. It's unlikely that any distro will be doing the same, so it's probably not an issue if this test fails on Linux in general. However,  I've just given this a go on Pop and MacOS and it's spitting out: ```rsync  version 3.2.3  protocol version 31``` as expected.

Let me know if this is a nuisance to you at all.
